---
- name: Configure vim
  block:
    - name: Ensure vim is installed
      apt:
        name: vim
        state: present

    - name: Create vim configuration directory
      file:
        path: /etc/vim
        state: directory
        mode: '0755'

    - name: Create vimrc.local file
      file:
        path: /etc/vim/vimrc.local
        state: touch
        mode: '0644'

    - name: Add vim settings line by line
      lineinfile:
        path: /etc/vim/vimrc.local
        line: "{{ item }}"
        state: present
        create: yes
      with_items:
        - "set background=dark"
        - "autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o"
        - "syntax on"
        - "set number"
        - "set ruler"
        - "set tabstop=4"
        - "set shiftwidth=4"
        - "set expandtab"
        - "set smartindent"
        - "set autoindent"
        - "set hlsearch"
        - "set incsearch"
        - "set ignorecase"
        - "set smartcase"
        - "set showmatch"
        - "set showcmd"
        - "set wildmenu"
        - "set wildmode=list:longest"
        - "set backspace=indent,eol,start"
        - "set laststatus=2"
        - "set statusline=%F%m%r%h%w\\ [FORMAT=%{&ff}]\\ [TYPE=%Y]\\ [POS=%l,%v][%p%%]\\ [BUFFER=%n]\\ %{strftime('%c')}"

  rescue:
    - name: Log vim configuration failure
      debug:
        msg: "Failed to configure vim. Please check the logs for more information."