---
# Handlers for NVIDIA driver role

- name: restart X server
  ansible.builtin.command:
    argv:
      - systemctl
      - restart
      - display-manager
  listen: restart display

- name: reboot system
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible due to NVIDIA driver installation"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  listen: reboot required